class AppStrings {
  AppStrings(this.code);

  static const supportedCodes = ['tr', 'en', 'de', 'fr', 'es', 'ar'];
  static const languageNames = {
    'tr': 'Türkçe',
    'en': 'English',
    'de': 'Deutsch',
    'fr': 'Français',
    'es': 'Español',
    'ar': 'العربية',
  };

  final String code;

  bool get isRtl => code == 'ar';

  String t(String key) => (_values[code] ?? _values['en']!)[key] ?? _values['en']![key] ?? key;

  static const _values = <String, Map<String, String>>{
    'tr': {
      'discover': 'Keşfet', 'recommend': 'Öneri', 'favorites': 'Favoriler', 'account': 'Hesabım',
      'discoverSubtitle': 'Yakınındaki gerçek menüleri keşfet', 'searchHint': 'Restoran, şehir veya yemek ara',
      'restaurantsFailed': 'Restoranlar alınamadı.', 'restaurantsEmpty': 'Bu aramayla restoran bulunamadı.',
      'restaurant': 'Restoran', 'reviews': 'yorum', 'open': 'Açık', 'closed': 'Kapalı',
      'favoriteQueued': 'Favorilere eklendi veya senkronizasyon sırasına alındı.',
      'syncing': 'Değişiklikler senkronize ediliyor…', 'pendingChanges': 'değişiklik bağlantı bekliyor',
      'syncedChanges': 'değişiklik senkronize edildi', 'retry': 'TEKRAR DENE', 'dismiss': 'KAPAT',
      'restaurantDetail': 'Restoran detayı', 'mapFailed': 'Harita uygulaması açılamadı.',
      'directions': 'YOL TARİFİ', 'favorite': 'FAVORİ', 'menu': 'Menü', 'menuEmpty': 'Menü henüz yayınlanmadı.',
      'hours': 'Çalışma saatleri', 'hoursEmpty': 'Çalışma saatleri belirtilmemiş.',
      'todayQuestion': 'Bugün ne yesem?', 'recommendSubtitle': 'Bütçene ve davranışlarına göre kişisel karar',
      'maxBudget': 'Azami bütçe', 'suggest': 'BANA ÖNER', 'meal': 'Yemek',
      'favoritesTitle': 'Favorilerim', 'favoritesSubtitle': 'Kaydettiğin restoran ve yemekler',
      'favoritesEmpty': 'Henüz favorin yok.', 'accountSubtitle': 'Profil, dil, senkronizasyon ve güvenlik',
      'user': 'Decidoo kullanıcısı', 'language': 'Dil', 'syncNow': 'ŞİMDİ SENKRONİZE ET', 'logout': 'ÇIKIŞ YAP',
      'languageSaved': 'Dil tercihi kaydedildi.',
      'mon': 'Pazartesi', 'tue': 'Salı', 'wed': 'Çarşamba', 'thu': 'Perşembe',
      'fri': 'Cuma', 'sat': 'Cumartesi', 'sun': 'Pazar',
    },
    'en': {
      'discover': 'Discover', 'recommend': 'Recommend', 'favorites': 'Favorites', 'account': 'Account',
      'discoverSubtitle': 'Discover real menus near you', 'searchHint': 'Search restaurant, city or meal',
      'restaurantsFailed': 'Restaurants could not be loaded.', 'restaurantsEmpty': 'No restaurants matched this search.',
      'restaurant': 'Restaurant', 'reviews': 'reviews', 'open': 'Open', 'closed': 'Closed',
      'favoriteQueued': 'Added to favorites or queued for synchronization.',
      'syncing': 'Synchronizing changes…', 'pendingChanges': 'changes waiting for connection',
      'syncedChanges': 'changes synchronized', 'retry': 'RETRY', 'dismiss': 'CLOSE',
      'restaurantDetail': 'Restaurant details', 'mapFailed': 'The maps application could not be opened.',
      'directions': 'DIRECTIONS', 'favorite': 'FAVORITE', 'menu': 'Menu', 'menuEmpty': 'The menu has not been published yet.',
      'hours': 'Opening hours', 'hoursEmpty': 'Opening hours are not available.',
      'todayQuestion': 'What should I eat today?', 'recommendSubtitle': 'A personal decision based on your budget and behavior',
      'maxBudget': 'Maximum budget', 'suggest': 'SUGGEST FOR ME', 'meal': 'Meal',
      'favoritesTitle': 'My favorites', 'favoritesSubtitle': 'Restaurants and meals you saved',
      'favoritesEmpty': 'You have no favorites yet.', 'accountSubtitle': 'Profile, language, synchronization and security',
      'user': 'Decidoo user', 'language': 'Language', 'syncNow': 'SYNC NOW', 'logout': 'LOG OUT',
      'languageSaved': 'Language preference saved.',
      'mon': 'Monday', 'tue': 'Tuesday', 'wed': 'Wednesday', 'thu': 'Thursday',
      'fri': 'Friday', 'sat': 'Saturday', 'sun': 'Sunday',
    },
    'de': {
      'discover': 'Entdecken', 'recommend': 'Empfehlung', 'favorites': 'Favoriten', 'account': 'Konto',
      'discoverSubtitle': 'Entdecke echte Speisekarten in deiner Nähe', 'searchHint': 'Restaurant, Stadt oder Gericht suchen',
      'restaurantsFailed': 'Restaurants konnten nicht geladen werden.', 'restaurantsEmpty': 'Keine Restaurants gefunden.',
      'restaurant': 'Restaurant', 'reviews': 'Bewertungen', 'open': 'Geöffnet', 'closed': 'Geschlossen',
      'favoriteQueued': 'Zu Favoriten hinzugefügt oder zur Synchronisierung vorgemerkt.',
      'syncing': 'Änderungen werden synchronisiert…', 'pendingChanges': 'Änderungen warten auf Verbindung',
      'syncedChanges': 'Änderungen synchronisiert', 'retry': 'ERNEUT VERSUCHEN', 'dismiss': 'SCHLIESSEN',
      'restaurantDetail': 'Restaurantdetails', 'mapFailed': 'Die Karten-App konnte nicht geöffnet werden.',
      'directions': 'ROUTE', 'favorite': 'FAVORIT', 'menu': 'Speisekarte', 'menuEmpty': 'Die Speisekarte ist noch nicht veröffentlicht.',
      'hours': 'Öffnungszeiten', 'hoursEmpty': 'Keine Öffnungszeiten angegeben.',
      'todayQuestion': 'Was soll ich heute essen?', 'recommendSubtitle': 'Persönliche Entscheidung nach Budget und Verhalten',
      'maxBudget': 'Maximales Budget', 'suggest': 'VORSCHLAGEN', 'meal': 'Gericht',
      'favoritesTitle': 'Meine Favoriten', 'favoritesSubtitle': 'Gespeicherte Restaurants und Gerichte',
      'favoritesEmpty': 'Noch keine Favoriten.', 'accountSubtitle': 'Profil, Sprache, Synchronisierung und Sicherheit',
      'user': 'Decidoo-Nutzer', 'language': 'Sprache', 'syncNow': 'JETZT SYNCHRONISIEREN', 'logout': 'ABMELDEN',
      'languageSaved': 'Spracheinstellung gespeichert.',
      'mon': 'Montag', 'tue': 'Dienstag', 'wed': 'Mittwoch', 'thu': 'Donnerstag',
      'fri': 'Freitag', 'sat': 'Samstag', 'sun': 'Sonntag',
    },
    'fr': {
      'discover': 'Découvrir', 'recommend': 'Suggestion', 'favorites': 'Favoris', 'account': 'Compte',
      'discoverSubtitle': 'Découvrez les vrais menus près de vous', 'searchHint': 'Rechercher restaurant, ville ou plat',
      'restaurantsFailed': 'Impossible de charger les restaurants.', 'restaurantsEmpty': 'Aucun restaurant trouvé.',
      'restaurant': 'Restaurant', 'reviews': 'avis', 'open': 'Ouvert', 'closed': 'Fermé',
      'favoriteQueued': 'Ajouté aux favoris ou mis en attente de synchronisation.',
      'syncing': 'Synchronisation des modifications…', 'pendingChanges': 'modifications en attente de connexion',
      'syncedChanges': 'modifications synchronisées', 'retry': 'RÉESSAYER', 'dismiss': 'FERMER',
      'restaurantDetail': 'Détails du restaurant', 'mapFailed': "Impossible d'ouvrir l'application de cartes.",
      'directions': 'ITINÉRAIRE', 'favorite': 'FAVORI', 'menu': 'Menu', 'menuEmpty': "Le menu n'est pas encore publié.",
      'hours': "Horaires d'ouverture", 'hoursEmpty': "Horaires d'ouverture indisponibles.",
      'todayQuestion': "Qu'est-ce que je mange aujourd'hui ?", 'recommendSubtitle': 'Une décision personnelle selon votre budget et vos habitudes',
      'maxBudget': 'Budget maximum', 'suggest': 'ME SUGGÉRER', 'meal': 'Plat',
      'favoritesTitle': 'Mes favoris', 'favoritesSubtitle': 'Restaurants et plats enregistrés',
      'favoritesEmpty': "Vous n'avez pas encore de favoris.", 'accountSubtitle': 'Profil, langue, synchronisation et sécurité',
      'user': 'Utilisateur Decidoo', 'language': 'Langue', 'syncNow': 'SYNCHRONISER', 'logout': 'SE DÉCONNECTER',
      'languageSaved': 'Préférence de langue enregistrée.',
      'mon': 'Lundi', 'tue': 'Mardi', 'wed': 'Mercredi', 'thu': 'Jeudi',
      'fri': 'Vendredi', 'sat': 'Samedi', 'sun': 'Dimanche',
    },
    'es': {
      'discover': 'Descubrir', 'recommend': 'Recomendar', 'favorites': 'Favoritos', 'account': 'Cuenta',
      'discoverSubtitle': 'Descubre menús reales cerca de ti', 'searchHint': 'Buscar restaurante, ciudad o plato',
      'restaurantsFailed': 'No se pudieron cargar los restaurantes.', 'restaurantsEmpty': 'No se encontraron restaurantes.',
      'restaurant': 'Restaurante', 'reviews': 'reseñas', 'open': 'Abierto', 'closed': 'Cerrado',
      'favoriteQueued': 'Añadido a favoritos o puesto en cola para sincronizar.',
      'syncing': 'Sincronizando cambios…', 'pendingChanges': 'cambios esperando conexión',
      'syncedChanges': 'cambios sincronizados', 'retry': 'REINTENTAR', 'dismiss': 'CERRAR',
      'restaurantDetail': 'Detalles del restaurante', 'mapFailed': 'No se pudo abrir la aplicación de mapas.',
      'directions': 'CÓMO LLEGAR', 'favorite': 'FAVORITO', 'menu': 'Menú', 'menuEmpty': 'El menú aún no está publicado.',
      'hours': 'Horario', 'hoursEmpty': 'No hay horario disponible.',
      'todayQuestion': '¿Qué como hoy?', 'recommendSubtitle': 'Una decisión personal según tu presupuesto y comportamiento',
      'maxBudget': 'Presupuesto máximo', 'suggest': 'SUGERIRME', 'meal': 'Plato',
      'favoritesTitle': 'Mis favoritos', 'favoritesSubtitle': 'Restaurantes y platos guardados',
      'favoritesEmpty': 'Aún no tienes favoritos.', 'accountSubtitle': 'Perfil, idioma, sincronización y seguridad',
      'user': 'Usuario de Decidoo', 'language': 'Idioma', 'syncNow': 'SINCRONIZAR AHORA', 'logout': 'CERRAR SESIÓN',
      'languageSaved': 'Preferencia de idioma guardada.',
      'mon': 'Lunes', 'tue': 'Martes', 'wed': 'Miércoles', 'thu': 'Jueves',
      'fri': 'Viernes', 'sat': 'Sábado', 'sun': 'Domingo',
    },
    'ar': {
      'discover': 'استكشف', 'recommend': 'اقتراح', 'favorites': 'المفضلة', 'account': 'حسابي',
      'discoverSubtitle': 'اكتشف قوائم الطعام الحقيقية القريبة منك', 'searchHint': 'ابحث عن مطعم أو مدينة أو وجبة',
      'restaurantsFailed': 'تعذر تحميل المطاعم.', 'restaurantsEmpty': 'لم يتم العثور على مطاعم.',
      'restaurant': 'مطعم', 'reviews': 'تقييمات', 'open': 'مفتوح', 'closed': 'مغلق',
      'favoriteQueued': 'تمت الإضافة إلى المفضلة أو قائمة المزامنة.',
      'syncing': 'جارٍ مزامنة التغييرات…', 'pendingChanges': 'تغييرات تنتظر الاتصال',
      'syncedChanges': 'تغييرات تمت مزامنتها', 'retry': 'إعادة المحاولة', 'dismiss': 'إغلاق',
      'restaurantDetail': 'تفاصيل المطعم', 'mapFailed': 'تعذر فتح تطبيق الخرائط.',
      'directions': 'الاتجاهات', 'favorite': 'المفضلة', 'menu': 'القائمة', 'menuEmpty': 'لم يتم نشر القائمة بعد.',
      'hours': 'ساعات العمل', 'hoursEmpty': 'ساعات العمل غير متوفرة.',
      'todayQuestion': 'ماذا آكل اليوم؟', 'recommendSubtitle': 'قرار شخصي حسب ميزانيتك وسلوكك',
      'maxBudget': 'الميزانية القصوى', 'suggest': 'اقترح لي', 'meal': 'وجبة',
      'favoritesTitle': 'مفضلاتي', 'favoritesSubtitle': 'المطاعم والوجبات المحفوظة',
      'favoritesEmpty': 'لا توجد مفضلات بعد.', 'accountSubtitle': 'الملف واللغة والمزامنة والأمان',
      'user': 'مستخدم Decidoo', 'language': 'اللغة', 'syncNow': 'مزامنة الآن', 'logout': 'تسجيل الخروج',
      'languageSaved': 'تم حفظ تفضيل اللغة.',
      'mon': 'الاثنين', 'tue': 'الثلاثاء', 'wed': 'الأربعاء', 'thu': 'الخميس',
      'fri': 'الجمعة', 'sat': 'السبت', 'sun': 'الأحد',
    },
  };
}
